# database services
# PVC (persistent volume claims) are storage request tickets issued by a pod
# used to access the PV 

# StatefulSets used to manage stateful workloads (db)
# deployments use random hashes, StatefulSets guarantee db pods to re-attach
# to the same disk volume after rescheduling

# clusterIP: None = headless service (unloadbalanced for same db access)


apiVersion: v1
kind: Service
metadata: 
  name: account-db
  namespace: expenseflow
  labels:
    app: account-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None
  selector:
    app: account-db

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: account-db
  namespace: expenseflow
  labels:
    app: account-db
spec:
  serviceName: account-db
  replicas: 1
  selector:
    matchLabels:
      app: account-db
  template:
    metadata:
      labels:
        app: account-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
              name: postgres

          env:
            - name: POSTGRES_USER
              value: "account_user"
            - name: POSTGRES_DB
              value: "account_db"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: expenseflow-secret
                  key: ACCOUNT_DB_PASSWORD
          
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U account_user -d account_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
          
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U account_user -d account_db"]
            initialDelaySeconds: 15
            periodSeconds: 10
          
          volumeMounts:
            - name: account-db-data
              mountPath: /var/lib/postgresql/data
  
  volumeClaimTemplates:
    - metadata:
        name: account-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi