apiVersion: v1
kind: PersistentVolume
metadata:
  name: account-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/account-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transaction-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/transaction-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: report-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/report-db
