workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

stages:
  - test
  - package
  - deploy

include:
  - local: 'k8s/k8s-deployment.yml'

default:
  tags:
    - devops
    - docker
    - ubuntu

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: "1"  # for cache mount

  DOCKER_CLIENT_TIMEOUT: "300"
  COMPOSE_HTTP_TIMEOUT: "300"

service-test:
  stage: test
  parallel:
    matrix:
      - SERVICE: [ account-service, transaction-service, report-service ]
  image: python:3.12-slim

  before_script:
    - echo "Installing Poetry..."
    - pip install --no-cache-dir poetry
    - poetry config virtualenvs.create false
  script:
    - echo "Testing $SERVICE..."
    - (cd $SERVICE && poetry install --no-root && PYTHONPATH=. pytest tests/ --cov=app)


docker-build:
  stage: package
  retry: 2
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
    
  before_script:
    - export DOCKER_BUILDKIT=1
    - echo "Logging into GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - |
      if [ -n "$DOCKERHUB_USERNAME" ] && [ -n "$DOCKERHUB_TOKEN" ]; then
        echo "Logging into Docker Hub..."
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin || echo "WARNING: Docker Hub login failed."
      fi
  script:
    - |
      for SERVICE in account-service transaction-service report-service; do
        echo "------------------------------------------------------"
        echo ">>>>> building and pushing $SERVICE image <<<<<"
        echo "------------------------------------------------------"
        docker pull "$CI_REGISTRY_IMAGE/$SERVICE:latest" || true
        docker build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from "$CI_REGISTRY_IMAGE/$SERVICE:latest" \
          -t "$CI_REGISTRY_IMAGE/$SERVICE:$CI_COMMIT_SHORT_SHA" \
          -t "$CI_REGISTRY_IMAGE/$SERVICE:latest" \
          ./$SERVICE
        docker push --all-tags "$CI_REGISTRY_IMAGE/$SERVICE"

        if [ -n "$DOCKERHUB_USERNAME" ]; then
          docker tag "$CI_REGISTRY_IMAGE/$SERVICE:$CI_COMMIT_SHORT_SHA" "$DOCKERHUB_USERNAME/expenseflow-$SERVICE:$CI_COMMIT_SHORT_SHA"
          docker tag "$CI_REGISTRY_IMAGE/$SERVICE:latest" "$DOCKERHUB_USERNAME/expenseflow-$SERVICE:latest"
          docker push --all-tags "$DOCKERHUB_USERNAME/expenseflow-$SERVICE"
        fi
      done

