
name: expenseflow

networks:
  expenseflow_net:
    driver: bridge

volumes:
  account_db_data:
  transaction_db_data:
  report_db_data: 

services:

# database setup

  account-db:

    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: ${ACCOUNT_DB_PASSWORD}
      POSTGRES_DB: account_db

    volumes:
      - account_db_data:/var/lib/postgresql/data
    
    networks:
      - expenseflow_net
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  transaction-db:
    
    image: postgres:16-alpine
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: ${TRANSACTION_DB_PASSWORD}
      POSTGRES_DB: transaction_db
    
    volumes:
      - transaction_db_data:/var/lib/postgresql/data
    
    networks:
      - expenseflow_net
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  report-db:
    
    image: postgres:16-alpine
    restart: unless-stopped
    
    environment:
      POSTGRES_USER: report_user
      POSTGRES_PASSWORD: ${REPORT_DB_PASSWORD}
      POSTGRES_DB: report_db
    
    volumes:
      - report_db_data:/var/lib/postgresql/data
    
    networks:
      - expenseflow_net
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

# services
  
  account-service:
    
    build:
      context: ./account-service
      dockerfile: Dockerfile 
    
    ports:
      - "8001:8000"

    environment:
      DATABASE_URL: ${ACCOUNT_DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    networks:
      - expenseflow_net
    
    depends_on:
      account-db:
        condition: service_healthy

  transaction-service:

    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: ${TRANSACTION_DATABASE_URL}
      ACCOUNT_SERVICE_URL: ${ACCOUNT_SERVICE_URL}
    
    networks:
      - expenseflow_net
    
    depends_on:
      transaction-db:
        condition: service_healthy

  report-service:
    
    build:
      context: ./report-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    
    environment:
      DATABASE_URL: ${REPORT_DATABASE_URL}
      ACCOUNT_SERVICE_URL: ${REPORT_ACCOUNT_SERVICE_URL}
      TRANSACTION_SERVICE_URL: ${REPORT_TRANSACTION_SERVICE_URL}
    
    networks:
      - expenseflow_net
    
    depends_on:
      report-db:
        condition: service_healthy
      account-service:
        condition: service_started
      transaction-service:
        condition: service_started
